const NOTIFICATION_TYPES = {
  SYSTEM: 'SYSTEM',
  RECORD_SUBMITTED: 'RECORD_SUBMITTED',
  RECORD_REVIEWED: 'RECORD_REVIEWED',
  RECORD_REJECTED: 'RECORD_REJECTED',
  RECORD_APPROVED: 'RECORD_APPROVED',
  COURSE_CREATED: 'COURSE_CREATED',
  COURSE_UPDATED: 'COURSE_UPDATED',
  COURSE_DEADLINE: 'COURSE_DEADLINE',
  REMINDER: 'REMINDER',
  WEEKLY_SUMMARY: 'WEEKLY_SUMMARY',
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  DOCTOR_ADDED: 'DOCTOR_ADDED',
  BULK_IMPORT_COMPLETED: 'BULK_IMPORT_COMPLETED',
  FINAL_APPROVAL_PENDING: 'FINAL_APPROVAL_PENDING',
  PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',
  SYSTEM_ALERT: 'SYSTEM_ALERT',
  AUDIT_ALERT: 'AUDIT_ALERT',
  REPORT: 'REPORT',
};

const NOTIFICATION_AUDIENCE_TYPES = {
  GLOBAL: 'GLOBAL',
  ROLE: 'ROLE',
  USER: 'USER',
};

const NOTIFICATION_CATEGORIES = {
  LEARNING: 'learning',
  SYSTEM: 'system',
  REPORT: 'report',
  DEADLINE: 'deadline',
  APPROVAL: 'approval',
  SECURITY: 'security',
  ADMIN: 'admin',
};

const NOTIFICATION_PRIORITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

const PRIORITY_ORDER = {
  CRITICAL: 4,
  HIGH: 3,
  MEDIUM: 2,
  LOW: 1,
};

module.exports = {
  NOTIFICATION_TYPES,
  NOTIFICATION_PRIORITIES,
  NOTIFICATION_AUDIENCE_TYPES,
  NOTIFICATION_CATEGORIES,
  PRIORITY_ORDER,
};
